import Foundation

/// DeepSeek (OpenAI-compatible) AI optimization layer (PRD §10, §13.3, AC-AI-*).
/// Only invoked when the user explicitly taps "AI 生成". Streams the result token
/// by token (AC-AI-03). On any failure the caller keeps the system translation
/// (AC-AI-06).
struct AIOptimizeService {
    static let shared = AIOptimizeService()

    static let defaultModel = "deepseek-chat"

    /// DeepSeek endpoint. Overridable via `OPTIONNOW_DEEPSEEK_BASE` (used by the
    /// in-process AI streaming test against a local mock server; also the seam for the
    /// P1 custom-Base-URL provider). Defaults to DeepSeek's OpenAI-compatible endpoint.
    private var endpoint: URL {
        if let base = ProcessInfo.processInfo.environment["OPTIONNOW_DEEPSEEK_BASE"],
           let url = URL(string: base) {
            return url
        }
        return URL(string: "https://api.deepseek.com/chat/completions")!
    }

    // MARK: - Prompt construction (PRD §10.1 / §10.2)

    private func systemPrompt(targetLang: String, toneModifier: String) -> String {
        """
        You are a professional translator and writing assistant. The user writes in Chinese and wants to send the text in \(targetLang). You will receive: 1. The original Chinese text. 2. A draft translation generated by the system translator. Your task: Refine the translation so it sounds natural, accurate, and ready to send. Output ONLY the final \(targetLang) text. Do not explain. Do not quote. Do not add extra notes. Preserve meaning, names, numbers, formatting, and line breaks. \(toneModifier)
        """
    }

    private func userMessage(targetLang: String, tone: String, source: String, systemTranslation: String) -> String {
        """
        Target language: \(targetLang)
        Tone: \(tone)

        Original Chinese: \(source)

        System translation draft: \(systemTranslation)
        """
    }

    private func makeRequest(apiKey: String,
                             model: String,
                             targetLangDisplay: String,
                             tone: Tone,
                             source: String,
                             systemTranslation: String,
                             stream: Bool) throws -> URLRequest {
        var request = URLRequest(url: endpoint)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
        request.timeoutInterval = 30

        let body: [String: Any] = [
            "model": model,
            "stream": stream,
            "messages": [
                ["role": "system",
                 "content": systemPrompt(targetLang: targetLangDisplay, toneModifier: tone.promptModifier)],
                ["role": "user",
                 "content": userMessage(targetLang: targetLangDisplay, tone: tone.displayName,
                                        source: source, systemTranslation: systemTranslation)]
            ]
        ]
        request.httpBody = try JSONSerialization.data(withJSONObject: body)
        return request
    }

    // MARK: - Streaming optimize (AC-AI-02/03/07)

    /// Streams content deltas. Throws a `TranslationError` on failure.
    func optimize(source: String,
                  systemTranslation: String,
                  targetLanguageDisplay: String,
                  tone: Tone,
                  apiKey: String,
                  model: String) -> AsyncThrowingStream<String, Error> {
        AsyncThrowingStream { continuation in
            let task = Task {
                do {
                    let request = try makeRequest(apiKey: apiKey,
                                                  model: model,
                                                  targetLangDisplay: targetLanguageDisplay,
                                                  tone: tone,
                                                  source: source,
                                                  systemTranslation: systemTranslation,
                                                  stream: true)
                    let (bytes, response) = try await URLSession.shared.bytes(for: request)

                    if let http = response as? HTTPURLResponse, http.statusCode != 200 {
                        // Drain body for a useful provider message.
                        var raw = ""
                        for try await line in bytes.lines { raw += line }
                        continuation.finish(throwing: Self.mapHTTPError(status: http.statusCode, body: raw))
                        return
                    }

                    for try await line in bytes.lines {
                        if Task.isCancelled { break }
                        guard line.hasPrefix("data:") else { continue }
                        let payload = line.dropFirst(5).trimmingCharacters(in: .whitespaces)
                        if payload == "[DONE]" { break }
                        guard let data = payload.data(using: .utf8),
                              let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                              let choices = obj["choices"] as? [[String: Any]],
                              let delta = choices.first?["delta"] as? [String: Any],
                              let content = delta["content"] as? String, !content.isEmpty else {
                            continue
                        }
                        continuation.yield(content)
                    }
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: Self.mapTransportError(error))
                }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    // MARK: - Key validation (AC-ST-01)

    /// Lightweight validation: a minimal non-stream request. Returns nil on success
    /// or a `TranslationError` describing the failure.
    func validate(apiKey: String, model: String) async -> TranslationError? {
        do {
            var request = try makeRequest(apiKey: apiKey,
                                          model: model,
                                          targetLangDisplay: "English",
                                          tone: .casual,
                                          source: "你好",
                                          systemTranslation: "Hello",
                                          stream: false)
            request.timeoutInterval = 15
            let (data, response) = try await URLSession.shared.data(for: request)
            guard let http = response as? HTTPURLResponse else { return .networkError }
            if http.statusCode == 200 { return nil }
            let body = String(data: data, encoding: .utf8) ?? ""
            return Self.mapHTTPError(status: http.statusCode, body: body)
        } catch {
            return Self.mapTransportError(error)
        }
    }

    // MARK: - Error mapping (AC-AI-06 / AC-ERR-07/08)

    private static func mapHTTPError(status: Int, body: String) -> TranslationError {
        switch status {
        case 401, 403: return .invalidKey
        case 429:      return .rateLimited
        case 500...599: return .providerError("服务端错误（\(status)）")
        default:
            return .providerError("请求失败（\(status)）")
        }
    }

    private static func mapTransportError(_ error: Error) -> TranslationError {
        if let urlError = error as? URLError {
            switch urlError.code {
            case .timedOut: return .timeout
            case .notConnectedToInternet, .networkConnectionLost, .cannotConnectToHost,
                 .cannotFindHost, .dnsLookupFailed:
                return .networkError
            default: return .networkError
            }
        }
        if error is TranslationError { return error as! TranslationError }
        return .providerError(error.localizedDescription)
    }
}
